#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

TOP_SRCDIR=${1}
shift

ALL_OPTIONS_H=${TOP_SRCDIR}/src/base/internal/options_incl.h

PACKAGES_SPEC=packages.spec
PACKAGES_SPEC_FULL=packages.fullspec

# do pre-cleanup
rm -f "$PACKAGES_SPEC" "$PACKAGES_SPEC_FULL" "packages_missing_efuns.autogen.h" \
  >/dev/null 2>&1 || true

PACKAGES=$("$@" -E -undef -dM $ALL_OPTIONS_H | grep PACKAGE_ | cut -d " " -f 2)

for P in $PACKAGES; do
	# get the package name, in uppercase
	P=${P#PACKAGE_} 
	# get the directory and file name
	DIR=$(echo $P | tr '[:upper:]' '[:lower:]')

	if [[ -e "${TOP_SRCDIR}/src/packages/$DIR/$DIR.spec" ]]; then
		echo "#include \"${TOP_SRCDIR}/src/packages/$DIR/$DIR.spec\"" >> $PACKAGES_SPEC
	else
		echo "Warning: ${TOP_SRCDIR}/src/packages/$DIR/$DIR.spec is missing."
	fi
done

"$@" -E -imacros $ALL_OPTIONS_H -P -x c++ $PACKAGES_SPEC > "$PACKAGES_SPEC_FULL"

# Generate the complement of the enabled package efun set. This lets the
# compiler distinguish a genuinely unknown function from an efun omitted by
# this build, without labeling duplicated efun declarations incorrectly.
MISSING_EFUNS_H=packages_missing_efuns.autogen.h

spec_efun_names() {
  sed -e 's://.*::' "$1" \
    | awk -F'(' '{ name = $1; sub(/^.*[[:space:]]/, "", name); \
                  if (name ~ /^[A-Za-z_][A-Za-z0-9_]*$/) print name }' \
    | sort -u || true
}

PRESENT_EFUNS=$(
  for P in $PACKAGES; do
    D=$(echo "${P#PACKAGE_}" | tr '[:upper:]' '[:lower:]')
    if [[ -e "${TOP_SRCDIR}/src/packages/$D/$D.spec" ]]; then
      spec_efun_names "${TOP_SRCDIR}/src/packages/$D/$D.spec"
    fi
  done | sort -u
)

{
  echo "/* Generated by tools/build_packages_genfiles.sh -- do not edit. */"
  echo "#ifndef PACKAGES_MISSING_EFUNS_AUTOGEN_H"
  echo "#define PACKAGES_MISSING_EFUNS_AUTOGEN_H"
  echo ""
  echo "struct missing_efun_t {"
  echo "  const char *name;"
  echo "  const char *package;"
  echo "};"
  echo ""
  echo "static const missing_efun_t missing_efuns[] = {"
} > "$MISSING_EFUNS_H"

for SPEC in "${TOP_SRCDIR}"/src/packages/*/*.spec; do
  DIR=$(basename "$(dirname "$SPEC")")
  PKG="PACKAGE_$(echo "$DIR" | tr '[:lower:]' '[:upper:]')"
  if echo "$PACKAGES" | grep -qx "$PKG"; then
    continue
  fi
  while read -r EFUN; do
    [[ -n "$EFUN" ]] || continue
    if echo "$PRESENT_EFUNS" | grep -qx "$EFUN"; then
      continue
    fi
    echo "    {\"$EFUN\", \"$PKG\"}," >> "$MISSING_EFUNS_H"
  done < <(spec_efun_names "$SPEC")
done

{
  echo "    {nullptr, nullptr},"
  echo "};"
  echo ""
  echo "#endif /* PACKAGES_MISSING_EFUNS_AUTOGEN_H */"
} >> "$MISSING_EFUNS_H"
